-- A Lua script to generate a build.ninja file
local config = {
    build_dir = "build",
    programs_dir = "programs",
    tohost_tests_dir = "programs/tohost_tests",
    link_script = "programs/link.ld",

    -- toolchain Configuration
    docker_image = "riscv-toolchain",
    tool_prefix = "riscv32-unknown-elf-",
    -- Includes the fix for finding macros.inc
    arch_flags = "-march=rv32i -mabi=ilp32 -Iprograms",

    -- orchestrator/simulation configuration
    orchestrator_test = "rv_processor_a1_unicycle.anyrom",
    simulator = "vsim"
}

-- docker command wrapper
local docker_user_flags = "--rm --user $$(id -u):$$(id -g) -v $${PROJ_DIR}:$${PROJ_DIR} --workdir $$(pwd)"
local docker_run = string.format("docker run %s %s", docker_user_flags, config.docker_image)

config.cc = string.format("%s %sgcc", docker_run, config.tool_prefix)
config.objcopy = string.format("%s %sobjcopy", docker_run, config.tool_prefix)

local ninja_file = {}

local function write(line)
    table.insert(ninja_file, line)
end

local function rule(name, command, description)
    write(string.format("rule %s", name))
    write(string.format("  command = %s", command))
    if description then
        write(string.format("  description = %s", description))
    end
    write("")
end

local function build(outputs, rule_name, inputs)
    outputs = type(outputs) == "string" and {outputs} or outputs
    inputs = type(inputs) == "string" and {inputs} or inputs
    write(string.format("build %s: %s %s", table.concat(outputs, " "), rule_name, table.concat(inputs, " ")))
end

write("# This file is generated by build.lua. DO NOT EDIT.\n")
write("ninja_required_version = 1.7\n")
write(string.format("builddir = %s", config.build_dir))
write(string.format("arch_flags = %s", config.arch_flags))
write(string.format("link_script = %s", config.link_script))
write(string.format("cc = %s", config.cc))
write(string.format("objcopy = %s", config.objcopy))
write("")

rule("configure", "lua build.lua", "Regenerating build.ninja")
rule("compile_asm", "$cc $arch_flags -c -o $out $in", "Compiling ASM $in")
rule("link_elf", "$cc $arch_flags -o $out $in -T $link_script -nostdlib -Wl,-Map,$out.map", "Linking ELF $out")
rule("create_rom", "$objcopy -O verilog --verilog-data-width 4 --only-section=.text* $in $out.tmp && cat $out.tmp | tr ' ' '\\n' | tr -d '\\r' > $out && rm -f $out.tmp", "Creating ROM $out")
rule("create_sram", "$objcopy -O verilog --verilog-data-width 4 --only-section=.data* --only-section=.sdata* --only-section=.bss* --only-section=.sbss* $in $out.tmp && cat $out.tmp | tr ' ' '\\n' | tr -d '\\r' > $out && rm -f $out.tmp", "Creating SRAM $out")
rule("do_clean", "rm -rf $builddir", "DELETING build directory ($builddir)")
write("")

build("build.ninja", "configure", "build.lua")

local test_files = {}
local find_cmd = string.format("find %s -type f -name '*.s'", config.tohost_tests_dir)
local find_pipe = io.popen(find_cmd)
if find_pipe then
    for filename in find_pipe:lines() do
        table.insert(test_files, filename)
    end
    find_pipe:close()
end

local all_hex_files = {}
for _, src_path in ipairs(test_files) do
    -- --- THE CRITICAL FIX ---
    -- 1. Get the base path by removing only the file extension.
    --    This preserves the full directory structure (e.g., "programs/tohost_tests/itype/xori")
    local base_path = src_path:gsub("%.s$", "")

    -- 2. Prepend the build directory variable to the full path.
    --    Result: "$builddir/programs/tohost_tests/itype/xori"
    local build_prefix = string.format("$builddir/%s", base_path)

    local obj_file = build_prefix .. ".o"
    local elf_file = build_prefix .. ".elf"
    local rom_file = build_prefix .. ".rom.hex"
    local sram_file = build_prefix .. ".sram.hex"

    build(obj_file, "compile_asm", src_path)
    build(elf_file, "link_elf", obj_file)
    build(rom_file, "create_rom", elf_file)
    build(sram_file, "create_sram", elf_file)

    -- Create a unique phony target for each test using its full path.
    build(base_path, "phony", {rom_file, sram_file})
    write("")

    table.insert(all_hex_files, rom_file)
    table.insert(all_hex_files, sram_file)
end

write("# Top-level aliases")
build("all", "phony", all_hex_files)
build("clean", "do_clean", "")
write("default all\n")

local ninja_out = io.open("build.ninja", "w")
if ninja_out then
    ninja_out:write(table.concat(ninja_file, "\n"))
    ninja_out:close()
    -- print("Generated build.ninja successfully.")
else
    error("Failed to open build.ninja for writing.")
end
