use crate::core::*;
use crate::silo::SiloResolver;
use crate::sw;

use std::path::PathBuf;
use std::fs;
use std::collections::HashMap;

#[derive(Clone, Debug)]
pub struct HardwareJob {
    pub testbench: String,
    pub param_set: String,
    pub simulator: String,
    pub silo_dir: PathBuf,
    pub artifact_paths: HashMap<String, PathBuf>,
}

pub fn resolve_hardware(
    config: &Config,
    binding: &Experiment,
    silo: &SiloResolver,
    shared: &HashMap<String, sw::ResolvedSharedJob>,
) -> anyhow::Result<Vec<HardwareJob>> {
    let mut jobs = Vec::new();
    let root = std::env::current_dir()?;

    let tb = config.testbenches.get(&binding.testbench)
        .ok_or_else(|| anyhow::anyhow!("TB '{}' not found", binding.testbench))?;

    for ps_name in &binding.param_sets {
        let ps = config.param_sets.get(ps_name)
            .ok_or_else(|| anyhow::anyhow!("ParamSet '{}' not found", ps_name))?;

        let hw_common_dir = silo.hw_common_dir(&tb.name, ps_name);
        fs::create_dir_all(&hw_common_dir)?;

        let mut replacements = HashMap::new();
        replacements.insert("PROJ_DIR".to_string(), root.to_string_lossy().to_string());
        replacements.insert("BUILD_DIR".to_string(), root.join(&silo.root).to_string_lossy().to_string());
        
        for (name, s_job) in shared {
            let abs_artifact = root.join(&s_job.artifact_path);
            replacements.insert(name.clone(), abs_artifact.to_string_lossy().to_string());
        }

        let input_f_path = root.join(&tb.filelist);
        if !input_f_path.exists() {
            anyhow::bail!("Source filelist not found: {}", input_f_path.display());
        }

        let original_content = fs::read_to_string(&input_f_path)?;
        let mut rendered_content = String::new();
        for line in original_content.lines() {
            let mut new_line = line.to_string();
            for (key, val) in &replacements {
                new_line = new_line.replace(&format!("$({})", key), val);
            }
            rendered_content.push_str(&new_line);
            rendered_content.push('\n');
        }

        let resolved_f_path = hw_common_dir.join("resolved.f");
        // println!("Writing common filelist to {:?}", resolved_f_path);
        fs::write(&resolved_f_path, rendered_content)?;

        let mut svh = String::from("// Generated by Harness\n");
        for (k, v) in &ps.defines {
            svh.push_str(&format!("`define {} {}\n", k, v));
        }
        fs::write(hw_common_dir.join("harness_params.svh"), svh)?;

        for sim_name in &binding.simulators {
            let sim = &config.simulators[sim_name];
            let silo_dir = silo.hw_dir(&tb.name, ps_name, sim_name);
            fs::create_dir_all(&silo_dir)?;

            let top_f_content = format!(
                "+incdir+{}\n-f {}\n",
                hw_common_dir.canonicalize()?.display(),
                resolved_f_path.canonicalize()?.display()
            );
            fs::write(silo_dir.join("top.f"), top_f_content)?;

            let mut artifact_paths = HashMap::new();
            for art in &sim.outputs {
                artifact_paths.insert(art.name.clone(), silo_dir.join(&art.filename));
            }
            
            // Link software dependencies (like cosim_dpi.a)
            for dep_name in &tb.sw_deps {
                if let Some(s_job) = shared.get(dep_name) {
                    artifact_paths.insert(dep_name.clone(), s_job.artifact_path.clone());
                }
            }

            jobs.push(HardwareJob {
                testbench: tb.name.clone(),
                param_set: ps_name.clone(),
                simulator: sim_name.clone(),
                silo_dir,
                artifact_paths,
            });
        }
    }
    Ok(jobs)
}
