use crate::core::*;
use crate::silo::SiloResolver;
use crate::sw;

use std::path::PathBuf;
use std::collections::HashMap;

#[derive(Clone, Debug)]
pub struct HardwareJob {
    pub testbench: String,
    pub param_set: String,
    pub simulator: String,
    pub silo_dir: PathBuf,
    pub artifact_paths: HashMap<String, PathBuf>,
}

pub fn resolve_hardware(
    config: &Config,
    binding: &Experiment,
    silo: &SiloResolver,
    shared: &HashMap<String, sw::ResolvedSharedJob>,
) -> anyhow::Result<Vec<HardwareJob>> {
    let mut jobs = Vec::new();
    let root = std::env::current_dir()?;

    let tb = config.testbenches.get(&binding.testbench)
        .ok_or_else(|| anyhow::anyhow!("TB '{}' not found", binding.testbench))?;

    for ps_name in &binding.param_sets {
        let ps = config.param_sets.get(ps_name)
            .ok_or_else(|| anyhow::anyhow!("ParamSet '{}' not found", ps_name))?;

        for sim_name in &binding.simulators {
            let sim = &config.simulators[sim_name];
            let silo_dir = silo.hw_dir(&tb.name, ps_name, sim_name);
            std::fs::create_dir_all(&silo_dir)?;

            let mut replacements = HashMap::new();
            replacements.insert("PROJ_DIR".to_string(), root.to_string_lossy().to_string());
            replacements.insert("BUILD_DIR".to_string(), root.join(&silo.root).to_string_lossy().to_string());
            for (name, s_job) in shared {
                replacements.insert(name.clone(), root.join(&s_job.artifact_path).to_string_lossy().to_string());
            }

            let original_f = std::fs::read_to_string(root.join(&tb.filelist))?;
            let mut rendered_f = String::new();
            for line in original_f.lines() {
                let mut r_line = line.to_string();
                for (k, v) in &replacements {
                    r_line = r_line.replace(&format!("$({})", k), v);
                }
                rendered_f.push_str(&r_line);
                rendered_f.push('\n');
            }
            let resolved_f_path = silo_dir.join("resolved.f");
            std::fs::write(&resolved_f_path, rendered_f)?;
            // --- END NEW ---

            let mut svh = String::from("// Generated by Harness\n");
            for (k, v) in &ps.defines {
                svh.push_str(&format!("`define {} {}\n", k, v));
            }
            std::fs::write(silo_dir.join("harness_params.svh"), svh)?;

            let top_f_content = format!(
                "+incdir+{}\n-f {}\n",
                silo_dir.canonicalize()?.display(),
                resolved_f_path.canonicalize()?.display() // 4. Point to resolved.f
            );
            std::fs::write(silo_dir.join("top.f"), top_f_content)?;

            let mut artifact_paths = HashMap::new();
            for art in &sim.outputs {
                artifact_paths.insert(art.name.clone(), silo_dir.join(&art.filename));
            }

            // 5. Add shared deps to HardwareJob so Ninja tracks them
            for dep_name in &tb.sw_deps {
                if let Some(s_job) = shared.get(dep_name) {
                    artifact_paths.insert(dep_name.clone(), s_job.artifact_path.clone());
                }
            }

            jobs.push(HardwareJob {
                testbench: tb.name.clone(),
                param_set: ps_name.clone(),
                simulator: sim_name.clone(),
                silo_dir,
                artifact_paths,
            });
        }
    }
    Ok(jobs)
}
