// harness/src/sim.rs
use crate::core::*;
use crate::hw::HardwareJob;
use crate::sw::SoftwareJob;
use crate::silo::SiloResolver;
use std::fs;
use std::path::PathBuf;

pub fn resolve_simulations(
    config: &Config,
    binding: &Binding,
    hw_jobs: &[HardwareJob],
    sw_jobs: &[SoftwareJob],
    silo: &SiloResolver,
) -> anyhow::Result<Vec<SimJob>> {
    let mut jobs = Vec::new();
    // Get the absolute root of the project so scripts are location-independent
    let root = std::env::current_dir()?;

    for hw in hw_jobs {
        for sw in sw_jobs {
            let suite = config.suites.get(&sw.suite_name)
                .ok_or_else(|| anyhow::anyhow!("Suite {} not found", sw.suite_name))?;
            
            let sim_dir = silo.sim_dir(
                &binding.name, &hw.processor, &hw.variant, &hw.testbench, &hw.simulator, &suite.name, &sw.rel_path
            );
            fs::create_dir_all(&sim_dir)?;

            let proc_spec = &config.processors[&hw.processor];
            let var_spec = &proc_spec.variants[&hw.variant];
            let sim_spec = &config.simulators[&hw.simulator];

            let template = var_spec.sim_templates.get(&hw.simulator)
                .or_else(|| proc_spec.sim_templates.get(&hw.simulator))
                .unwrap_or(&sim_spec.default_run_rule);

            let mut cmd = template.clone();
            let mut deps = Vec::new();

            // 1. Resolve HW Artifacts using ABSOLUTE paths for the script
            for (logical, path) in &hw.artifact_paths {
                let abs_path = root.join(path); 
                cmd = cmd.replace(&format!("${}", logical), &abs_path.to_string_lossy());
                deps.push(path.clone());
            }

            // 2. Resolve SW Artifacts using ABSOLUTE paths for the script
            for action in &sw.actions {
                for (logical, path_str) in &action.variables {
                    let placeholder = format!("${}", logical);
                    if cmd.contains(&placeholder) {
                        let abs_path = root.join(path_str);
                        cmd = cmd.replace(&placeholder, &abs_path.to_string_lossy());
                        deps.push(PathBuf::from(path_str));
                    }
                }
            }

            // 3. Aggregate Plusargs
            let mut pa = proc_spec.plusargs.clone();
            pa.extend(var_spec.plusargs.clone());
            pa.extend(suite.plusargs.clone());
            if let Some(ov) = suite.program_overrides.get(&sw.program_id) {
                pa.extend(ov.plusargs.clone());
            }
            cmd = cmd.replace("$plusargs", &pa.join(" "));

            // 4. Seed run.sh with Absolute Paths
            let script_path = sim_dir.join("run.sh");
            let abs_sim_dir = root.join(&sim_dir);
            let script_content = format!(
                "#!/usr/bin/env bash\n# Generated by Harness\n# Silo: {}\n\n{}\n",
                abs_sim_dir.display(), cmd
            );
            fs::write(&script_path, script_content)?;

            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let mut perms = fs::metadata(&script_path)?.permissions();
                perms.set_mode(0o755);
                fs::set_permissions(&script_path, perms)?;
            }

            jobs.push(SimJob {
                silo_dir: sim_dir,
                run_cmd: cmd,
                dependencies: deps,
            });
        }
    }
    Ok(jobs)
}

pub struct SimJob {
    pub silo_dir: PathBuf,
    pub run_cmd: String,
    pub dependencies: Vec<PathBuf>,
}
