TOP_MODULE     := top_tb_wrapper

COMPILER       := iverilog
COMPILE_FLAGS  := -g2012 -Wall $(SV_FILES) -s $(TOP_MODULE)
COMPILED_FILE  := $(BUILD_DIR)/sim.vvp
COMPILE_COMMAND := $(COMPILER) -o $(COMPILED_FILE) $(COMPILE_FLAGS)

WAVE_FILE      ?= $(BUILD_DIR)/waveform.vcd
SIMULATOR      := vvp
SIM_FLAGS      := +VCD_FILE=$(WAVE_FILE) -fst $(PLUSARGS)
SIM_COMMAND    := $(SIMULATOR) $(COMPILED_FILE) $(SIM_FLAGS)
CLEAN_COMMAND  := rm -rf $(BUILD_DIR)
