TOP_MODULE     := top_tb_wrapper

COMPILER       := iverilog
COMPILE_FLAGS  := -g2012 -Wall $(SV_FILES) -s $(TOP_MODULE)
COMPILED_FILE  := $(BUILD_DIR)/sim.vvp
COMPILE_COMMAND := $(COMPILER) -o $(COMPILED_FILE) $(COMPILE_FLAGS)

SIMULATOR      := vvp
SIM_FLAGS      := +VCD_FILE=waveform.vcd
SIM_COMMAND    := $(SIMULATOR) $(COMPILED_FILE) $(SIM_FLAGS)
